# Generated by Django 6.0.2 on 2026-02-16 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
